config/routes.rb
Rails.application.routes.draw do
  root 'my_profiles#index'

  resources :profile_comments
  post '/profile_comments/spin_comment', to: "profile_comments#spin_comment", as: 'spin_comment'

  resources :my_profile_statistics
  resources :my_profiles do
    get 'fetch_users', to: 'my_profiles#fetch_users', as: 'fetch_users'
  end
  get '/my_profile/:id', to: 'my_profiles#automated_profile_promotion', as: 'automated_profile_promotion'
  post '/follow_people/:id', to: 'my_profiles#follow_people', as: 'follow_people'
  get '/unfollow_people/:id', to: 'my_profiles#unfollow_people', as: 'unfollow_people'
  get '/test/:id', to: 'my_profiles#test', as: 'test'
  
  
  resources :pages do
    resources :photos
  end
  get '/page/:page_id/fetch_photos', to: 'photos#fetch_all_photos_of_page', as: 'fetch_pages_photos'

  resources :photos do
    resources :comments
    resources :likes
  end

  resources :users
  get '/update_users_details', to: 'users#update_users_details', as: 'update_users_details'
  get '/delete_unwanted_users', to: 'users#delete_unwanted_users', as: 'delete_unwanted_users'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user

  def self.save_photos_comments(photos_comments)
    photos_comments.each do |photo_comments|
      user = User.find_by(profile_url: photo_comments[:profile_url])
      if user.nil?
        user = User.create(profile_url: photo_comments[:profile_url], like_count: 0, comments_count: 1)
      else
        user.increment_comments
      end
      Comment.create(user_id: user.id, photo_id: photo_comments[:photo_id], content: photo_comments[:comment_content])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @photo = Photo.find(params[:photo_id])
    @comments = @photo.comments
  end

  def show;end

  def new
    @comment = Comment.new
  end

  def edit;end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :photo_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for(@comment) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .field
    = f.label :photo_id
    %br/
    = f.text_field :photo_id
  .field
    = f.label :content
    %br/
    = f.text_field :content
  .actions
    = f.submit

app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form'
= link_to 'Show', @comment
|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%p#notice= notice
%h1
  Listing Comments -  This photo have #{@comments.count} comments!
%table
  %thead
    %tr
      %th User
      %th Photo
      %th Page
      %th{:colspan => "3"}
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.user_id
        %td= comment.photo_id
        %td= comment.content
        %td= link_to 'Show', photo_comment_path(params[:photo_id],comment.id)
        %td= link_to 'Edit', edit_photo_comment_path(params[:photo_id], comment)
        %td= link_to 'Destroy', [@photo, comment], method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_photo_comment_path

app/views/comments/new.html.haml
%h1 New Comment
= render 'form'
= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @comment.user_id
%p
  %strong Photo:
  = @comment.photo_id
%p
  %strong Page:
  = @comment.content
= link_to 'Edit', edit_comment_path(@comment)
|
= link_to 'Back', comments_path