config/routes.rb
Rails.application.routes.draw do
  root 'my_profiles#index'

  resources :profile_comments
  post '/profile_comments/spin_comment', to: "profile_comments#spin_comment", as: 'spin_comment'

  resources :my_profile_statistics
  resources :my_profiles do
    get 'fetch_users', to: 'my_profiles#fetch_users', as: 'fetch_users'
  end
  get '/my_profile/:id', to: 'my_profiles#automated_profile_promotion', as: 'automated_profile_promotion'
  post '/follow_people/:id', to: 'my_profiles#follow_people', as: 'follow_people'
  get '/unfollow_people/:id', to: 'my_profiles#unfollow_people', as: 'unfollow_people'
  get '/test/:id', to: 'my_profiles#test', as: 'test'
  
  
  resources :pages do
    resources :photos
  end
  get '/page/:page_id/fetch_photos', to: 'photos#fetch_all_photos_of_page', as: 'fetch_pages_photos'

  resources :photos do
    resources :comments
    resources :likes
  end

  resources :users
  get '/update_users_details', to: 'users#update_users_details', as: 'update_users_details'
  get '/delete_unwanted_users', to: 'users#delete_unwanted_users', as: 'delete_unwanted_users'
end

app/models/user.rb
require 'nokogiri'   
require 'open-uri'

class User < ActiveRecord::Base
  has_many :comments, dependent: :delete_all
  has_many :likes

  scope :all_users_related_to_profile, -> (id) { joins(:comments => [:photo => [:page => :my_profile]]).where('my_profile_id = ?', id) }
  scope :good_to_follow, -> (account, limit) { where("latest_hashtags RLIKE (?) or biography RLIKE (?)", account.related_hashtags.gsub(' ','|'), account.related_hashtags.gsub(' ','|')).where("users.followings_count < 600").where("users.is_followed is NOT true").limit(limit) }

  scope :without_posts, -> { where('posts_count <= ?', 2) }
  scope :with_more_than_1k_following, -> { where('followings_count > ?', 1000) }
  scope :with_more_than_6k_followers, -> { where('followers_count > ?', 6000) }
  scope :with_more_than_20_comments, -> { where('comments_count >= ?', 20) }
  scope :with_many_posts_no_hashtags, -> { where('posts_count >= ?', 1000).where(hashtags: '') }
  scope :many_posts_no_hashtags, -> { where('posts_count >= ?', 1800).where(hashtags: '') }
  scope :commented_with_only_emojis, -> { where('id in (?)', Comment.where(content: '').pluck(:user_id).uniq) }

  def increment_comments
    self.comments_count += 1
    save!
  end

  def self.fetch_user_details(users)
    users.each do |user|
      profile = Nokogiri::HTML(open("#{user.profile_url}"))
      profile = eval(profile.text.split("window._sharedData")[1].split("window.__")[0].split("!function")[0][3..-1].gsub!('null', 'nil'))
      profile = profile[:entry_data][:ProfilePage][0][:graphql][:user]
      website = profile[:external_url].nil? ? '' : profile[:external_url] 
      biography = (profile[:biography] + website).encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
      hashtags = []
      profile[:edge_owner_to_timeline_media][:edges][0..12].each do |photo_details|
        if !photo_details[:node][:edge_media_to_caption][:edges][0].nil?
          hashtags += photo_details[:node][:edge_media_to_caption][:edges][0][:node][:text].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '').scan(/#\w+/).flatten
        end
      end
      user.biography = biography
      user.is_private = profile[:is_private]
      user.latest_hashtags = hashtags.uniq.join(' ')
      user.posts_count = profile[:edge_owner_to_timeline_media][:count]
      user.followers_count = profile[:edge_followed_by][:count]
      user.followings_count = profile[:edge_follow][:count]
      user.save!
      sleep(rand(5..12))
    end
  end

  def self.delete_unwanted_users
    User.without_posts.delete_all
    User.with_more_than_1k_following.delete_all
    User.with_more_than_6k_followers.delete_all
    User.with_more_than_20_comments.delete_all
    User.commented_with_only_emojis.delete_all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.where("latest_hashtags LIKE ?", '%wood%').where("followings_count < 400")
  end

  def show;end

  def new
    @user = User.new
  end

  def edit;end

  def update_users_details
    User.fetch_user_details(User.where(:biography => nil))
  end

  def delete_unwanted_users 
    User.delete_unwanted_users
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:profile_url, :like_count, :comment_count)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :profile_url
    %br/
    = f.text_area :profile_url
  .field
    = f.label :like_count
    %br/
    = f.text_field :like_count
  .field
    = f.label :comments_count
    %br/
    = f.text_field :comments_count
  .field
    = f.label :posts_count
    %br/
    = f.text_field :posts_count
  .field
    = f.label :followers_count
    %br/
    = f.text_field :followers_count
  .field
    = f.label :followings_count
    %br/
    = f.text_field :followings_count
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%p#notice= notice
= link_to "Update Users Details", update_users_details_path
= link_to "Delete unwanted Users", delete_unwanted_users_path
%h1 Listing Users
%table
  %thead
    %tr
      %th Profile url
      %th Like count
      %th Comments count
      %th Posts count
      %th Followers
      %th Followings
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.profile_url, user.profile_url
        %td= user.like_count
        %td= user.comments_count
        %td= user.posts_count
        %td= user.followers_count
        %td= user.followings_count
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Profile url:
  = @user.profile_url
%p
  %strong Like count:
  = @user.like_count
%p
  %strong Comment count:
  = @user.comments_count
%p
  %strong Posts count:
  = @user.posts_count
%p
  %strong Followers count:
  = @user.followers_count
%p
  %strong Followings count:
  = @user.followings_count
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path