config/routes.rb
Rails.application.routes.draw do
  root 'my_profiles#index'

  resources :profile_comments
  post '/profile_comments/spin_comment', to: "profile_comments#spin_comment", as: 'spin_comment'

  resources :my_profile_statistics
  resources :my_profiles do
    get 'fetch_users', to: 'my_profiles#fetch_users', as: 'fetch_users'
  end
  get '/my_profile/:id', to: 'my_profiles#automated_profile_promotion', as: 'automated_profile_promotion'
  post '/follow_people/:id', to: 'my_profiles#follow_people', as: 'follow_people'
  get '/unfollow_people/:id', to: 'my_profiles#unfollow_people', as: 'unfollow_people'
  get '/test/:id', to: 'my_profiles#test', as: 'test'
  
  
  resources :pages do
    resources :photos
  end
  get '/page/:page_id/fetch_photos', to: 'photos#fetch_all_photos_of_page', as: 'fetch_pages_photos'

  resources :photos do
    resources :comments
    resources :likes
  end

  resources :users
  get '/update_users_details', to: 'users#update_users_details', as: 'update_users_details'
  get '/delete_unwanted_users', to: 'users#delete_unwanted_users', as: 'delete_unwanted_users'
end

app/models/my_profile.rb
class MyProfile < ApplicationRecord
  has_many :statistics, foreign_key: "profile_id", class_name: "MyProfileStatistic"
  has_many :comments, foreign_key: "profile_id", class_name: "ProfileComment"
  has_many :pages

  def login(browser=nil)
    browser = Watir::Browser.new :chrome if browser.nil?
    browser.goto("https://www.instagram.com/accounts/login/")
    sleep(2)
    browser.text_field(class: '_ph6vk', index: 0).set(username)
    sleep(0.5)
    browser.text_field(class: '_ph6vk', index: 1).set(password)
    sleep(0.5)
    browser.form(:class, '_3jvtb').submit
    sleep(6)
    return browser
  end
end

app/controllers/my_profiles_controller.rb
class MyProfilesController < ApplicationController
  before_action :set_my_profile, except: [:index, :new, :create, :fetch_users]

  def index
    @my_profiles = MyProfile.all
  end

  def show;end

  def new
    @my_profile = MyProfile.new
  end

  def edit; end

  def create
    @my_profile = MyProfile.new(my_profile_params)
    InstagramService.fetch_page_details(@my_profile)
    respond_to do |format|
      if @my_profile.save
        format.html { redirect_to @my_profile, notice: 'My profile was successfully created.' }
        format.json { render :show, status: :created, location: @my_profile }
      else
        format.html { render :new }
        format.json { render json: @my_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @my_profile.update(my_profile_params)
        InstagramService.fetch_page_details(@my_profile)
        format.html { redirect_to @my_profile, notice: 'My profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_profile }
      else
        format.html { render :edit }
        format.json { render json: @my_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @my_profile.destroy
    respond_to do |format|
      format.html { redirect_to my_profiles_url, notice: 'My profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # REVIEW: This action is too stacked
  def automated_profile_promotion
    InstagramService.fetch_page_details(@my_profile)
    pages_urls = @my_profile.pages.pluck(:url)
    photos_comments = Page.fetch_pages_photos_comments(pages_urls)
    Comment.save_photos_comments(photos_comments)
    User.fetch_user_details(User.where(:biography => nil))
    User.delete_unwanted_users
    InstagramService.like_and_follow_users(@my_profile, 5)
    redirect_to my_profiles_path
  end

  def follow_people
    InstagramService.fetch_page_details(@my_profile)
    InstagramService.like_and_follow_users(@my_profile, params[:my_profile][:limit])
    redirect_to my_profiles_path
  end

  def unfollow_people
    # TODO: desreved way -> @my_profile.unfollow_people
    InstagramService.unfollow_people(@my_profile)
  end

  def fetch_users
    @my_profile = MyProfile.find(params[:my_profile_id])
    photos = Page.fetch_pages_photos_comments(@my_profile.pages.pluck(:url))
    Comment.save_photos_comments(photos)
    User.fetch_user_details(User.where(:biography => nil))
    User.delete_unwanted_users
    redirect_to my_profile_path(@my_profile)
  end

  def test
    InstagramService.post_image(@my_profile)
  end

  private
    def set_my_profile
      @my_profile = MyProfile.find(params[:id])
    end

    def my_profile_params
      params.require(:my_profile).permit(:url, :username, :password, :related_hashtags)
    end
end

app/helpers/my_profiles_helper.rb
module MyProfilesHelper
end

app/views/my_profiles/_follow_people_form.html.haml
%td.formatted
  = form_for profile, method: :post, url: follow_people_path(profile) do |f|
    = f.number_field :limit, class: 'number_select', value: 1
    = f.submit "Follow", class: 'submit_form'

app/views/my_profiles/_form.html.haml
= form_with(model: my_profile, local: true) do |form|
  - if my_profile.errors.any?
    #error_explanation
      %h2
        = pluralize(my_profile.errors.count, "error")
        prohibited this my_profile from being saved:
      %ul
        - my_profile.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :url
    = form.text_area :url
  .field
    = form.label :username
    = form.text_area :username
  .field
    = form.label :password
    = form.text_area :password
  .field
    = form.label :related_hashtags
    = form.text_area :related_hashtags
  .actions
    = form.submit

app/views/my_profiles/edit.html.haml
%h1 Editing My Profile
= render 'form', my_profile: @my_profile
= link_to 'Show', @my_profile
|
= link_to 'Back', my_profiles_path

app/views/my_profiles/index.html.haml
%div#celownik
  Witam panstwa
%p#notice= notice
%h1 My Profiles
%table
  %thead
    %tr
      %th Url
      %th Username
      %th Followers Count
      %th Followings Count
      %th{:colspan => "4"}
      %th Follow People
  %tbody
    - @my_profiles.each do |my_profile|
      %tr
        %td= link_to my_profile.url, my_profile.url
        %td= my_profile.username
        %td= my_profile.statistics.last.followers_count
        %td= my_profile.statistics.last.followings_count
        %td= link_to 'Show', my_profile
        %td= link_to 'Edit', edit_my_profile_path(my_profile)
        %td= link_to 'Destroy', my_profile, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Automate Promote', automated_profile_promotion_path(my_profile)
        = render 'follow_people_form', profile: my_profile
        %td= link_to 'Unfollow People', unfollow_people_path(my_profile)
%br/
= link_to 'New My Profile', new_my_profile_path

= javascript_pack_tag 'tic_tac'

app/views/my_profiles/new.html.haml
%h1 New My Profile
= render 'form', my_profile: @my_profile
= link_to 'Back', my_profiles_path

app/views/my_profiles/show.html.haml
%p#notice= notice
%p
  %strong Url:
  = @my_profile.url
%p
  %strong Username:
  = @my_profile.username
%p
  %strong Password:
  = @my_profile.password
= link_to 'Fetch Related Users', my_profile_fetch_users_path(@my_profile)
= link_to 'Edit', edit_my_profile_path(@my_profile)
|
= link_to 'Back', my_profiles_path