config/routes.rb
Rails.application.routes.draw do
  root 'my_profiles#index'

  resources :profile_comments
  post '/profile_comments/spin_comment', to: "profile_comments#spin_comment", as: 'spin_comment'

  resources :my_profile_statistics
  resources :my_profiles do
    get 'fetch_users', to: 'my_profiles#fetch_users', as: 'fetch_users'
  end
  get '/my_profile/:id', to: 'my_profiles#automated_profile_promotion', as: 'automated_profile_promotion'
  post '/follow_people/:id', to: 'my_profiles#follow_people', as: 'follow_people'
  get '/unfollow_people/:id', to: 'my_profiles#unfollow_people', as: 'unfollow_people'
  get '/test/:id', to: 'my_profiles#test', as: 'test'
  
  
  resources :pages do
    resources :photos
  end
  get '/page/:page_id/fetch_photos', to: 'photos#fetch_all_photos_of_page', as: 'fetch_pages_photos'

  resources :photos do
    resources :comments
    resources :likes
  end

  resources :users
  get '/update_users_details', to: 'users#update_users_details', as: 'update_users_details'
  get '/delete_unwanted_users', to: 'users#delete_unwanted_users', as: 'delete_unwanted_users'
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Profiles", my_profiles_path
= link_to "Pages", pages_path
= link_to "Photos", page_photos_path(1)
= link_to "Users", users_path
= link_to "Comments", photo_comment_path(1,2)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :integrity => "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", :rel => "stylesheet"}/
    %title= content_for?(:title) ? yield(:title) : "Instagram Scraper"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "Instagram Scraper"}", :name => "description"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render partial: 'layouts/navigation'
      = render 'layouts/messages'
    %main{:role => "main"}
      = yield
      = javascript_pack_tag 'application'